language: node_js
node_js:
  - 'node'

script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $DEPLOY_TOKEN
  keep_history: true
  on:
    branch: dev
